ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of GldGrv_UFO_benj_160_2'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_2372 = ', GC_2372
      WRITE(*,2) 'GC_2398 = ', GC_2398
      WRITE(*,2) 'GC_2238 = ', GC_2238
      WRITE(*,2) 'GC_2249 = ', GC_2249
      WRITE(*,2) 'GC_2288 = ', GC_2288
      WRITE(*,2) 'GC_2388 = ', GC_2388
