#!/bin/bash

depth=1
njob=bjob
t=`find ./par_* -maxdepth $depth -name "${njob}*" |wc -l`
r=`find ./par_* -maxdepth $depth -name "run.${njob}*" |wc -l`
w=`find ./par_* -maxdepth $depth -name "wait.${njob}*" |wc -l`
d=`find ./par_* -maxdepth $depth -name "done.${njob}*" |wc -l`

countlimit=10 # for nevent < 10k
#countlimit=50 # for nevent < 100k
echo "waiting while finishing jobs on cluster"
icount=0
while [[  $d -lt $t  ]]; do    
    echo $w $r $d $t
#    rm -f ../status
#    echo $w $r $d $t > ../status
    if [ $t -eq 1 ];then
	if [ $icount -gt $countlimit ];then
	    break
	fi
	icount=`expr $icount + 1`
    else
	if [ $d -gt 0 ];then
	    if [ $r -eq $r_save ];then
		icount=`expr $icount + 1`
	    else
		icount=0
	    fi
	    if [ $icount -gt $countlimit ];then
		break
	    fi
	fi
    fi
    r_save=$r
    sleep 10
    t=`find ./par_* -maxdepth $depth -name "${njob}*" |wc -l`
    r=`find ./par_* -maxdepth $depth -name "run.${njob}*" |wc -l`
    w=`find ./par_* -maxdepth $depth -name "wait.${njob}*" |wc -l`
    d=`find ./par_* -maxdepth $depth -name "done.${njob}*" |wc -l`
done
echo $w $r $d $t

sleep 20