C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     P(2,3)*ProjM(2,1)
C     
      SUBROUTINE FRS1_0(F1, R2, S3, COUP,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 S3(*)
      COMPLEX*16 R2(*)
      REAL*8 P3(0:3)
      COMPLEX*16 F1(*)
      COMPLEX*16 VERTEX
      COMPLEX*16 COUP
      COMPLEX*16 TMP8
      P3(0) = DBLE(S3(1))
      P3(1) = DBLE(S3(2))
      P3(2) = DIMAG(S3(2))
      P3(3) = DIMAG(S3(1))
      TMP8 = (F1(3)*-1D0*(P3(1)*R2(7)+P3(2)*R2(11)+P3(3)*R2(15)
     $ -P3(0)*R2(3))-F1(4)*(P3(1)*R2(8)+P3(2)*R2(12)+P3(3)*R2(16)
     $ -P3(0)*R2(4)))
      VERTEX = COUP*-CI * TMP8*S3(3)
      END


C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     P(2,3)*ProjM(2,1)
C     
      SUBROUTINE FRS1_5_0(F1, R2, S3, COUP1, COUP2,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 S3(*)
      COMPLEX*16 R2(*)
      REAL*8 P3(0:3)
      COMPLEX*16 F1(*)
      COMPLEX*16 COUP1
      COMPLEX*16 COUP2
      COMPLEX*16 VERTEX
      COMPLEX*16 TMP
      CALL FRS1_0(F1,R2,S3,COUP1,VERTEX)
      CALL FRS5_0(F1,R2,S3,COUP2,TMP)
      VERTEX = VERTEX + TMP
      END


C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     P(2,3)*ProjM(2,1)
C     
      SUBROUTINE FRS1_2_3_6_7_8_0(F1, R2, S3, COUP1, COUP2, COUP3
     $ , COUP4, COUP5, COUP6,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP5
      COMPLEX*16 S3(*)
      COMPLEX*16 R2(*)
      REAL*8 P3(0:3)
      COMPLEX*16 F1(*)
      COMPLEX*16 COUP1
      COMPLEX*16 COUP2
      COMPLEX*16 COUP3
      COMPLEX*16 VERTEX
      COMPLEX*16 TMP
      COMPLEX*16 COUP6
      COMPLEX*16 COUP4
      CALL FRS1_0(F1,R2,S3,COUP1,VERTEX)
      CALL FRS2_0(F1,R2,S3,COUP2,TMP)
      VERTEX = VERTEX + TMP
      CALL FRS3_0(F1,R2,S3,COUP3,TMP)
      VERTEX = VERTEX + TMP
      CALL FRS6_0(F1,R2,S3,COUP4,TMP)
      VERTEX = VERTEX + TMP
      CALL FRS7_0(F1,R2,S3,COUP5,TMP)
      VERTEX = VERTEX + TMP
      CALL FRS8_0(F1,R2,S3,COUP6,TMP)
      VERTEX = VERTEX + TMP
      END


C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     P(2,3)*ProjM(2,1)
C     
      SUBROUTINE FRS1_3_0(F1, R2, S3, COUP1, COUP2,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP5
      COMPLEX*16 S3(*)
      COMPLEX*16 R2(*)
      REAL*8 P3(0:3)
      COMPLEX*16 F1(*)
      COMPLEX*16 COUP1
      COMPLEX*16 COUP2
      COMPLEX*16 COUP3
      COMPLEX*16 VERTEX
      COMPLEX*16 TMP
      COMPLEX*16 COUP6
      COMPLEX*16 COUP4
      CALL FRS1_0(F1,R2,S3,COUP1,VERTEX)
      CALL FRS3_0(F1,R2,S3,COUP2,TMP)
      VERTEX = VERTEX + TMP
      END


