C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     (Gamma(2,2,-1)*ProjM(-1,1)) * C(51,2) * C(52,1)
C     
      SUBROUTINE FRS2C1_0(R2, F1, S3, COUP,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 TMP12
      COMPLEX*16 S3(*)
      COMPLEX*16 R2(*)
      COMPLEX*16 F1(*)
      COMPLEX*16 VERTEX
      COMPLEX*16 COUP
      TMP12 = (F1(3)*(R2(10)+R2(17)-CI*(R2(14))-R2(5))+F1(4)*(R2(9)
     $ +CI*(R2(13))-R2(6)-R2(18)))
      VERTEX = COUP*-CI * TMP12*S3(3)
      END


C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     (Gamma(2,2,-1)*ProjM(-1,1)) * C(51,2) * C(52,1)
C     
      SUBROUTINE FRS2_4_7_9C1_0(R2, F1, S3, COUP1, COUP2, COUP3, COUP4
     $ ,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 S3(*)
      COMPLEX*16 R2(*)
      COMPLEX*16 F1(*)
      COMPLEX*16 COUP1
      COMPLEX*16 COUP2
      COMPLEX*16 COUP3
      COMPLEX*16 VERTEX
      COMPLEX*16 TMP
      COMPLEX*16 COUP4
      CALL FRS2C1_0(R2,F1,S3,COUP1,VERTEX)
      CALL FRS4C1_0(R2,F1,S3,COUP2,TMP)
      VERTEX = VERTEX + TMP
      CALL FRS7C1_0(R2,F1,S3,COUP3,TMP)
      VERTEX = VERTEX + TMP
      CALL FRS9C1_0(R2,F1,S3,COUP4,TMP)
      VERTEX = VERTEX + TMP
      END


