C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     P(2,3)*ProjP(2,1)
C     
      SUBROUTINE FRS6_0(F1, R2, S3, COUP,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 S3(*)
      COMPLEX*16 R2(*)
      REAL*8 P3(0:3)
      COMPLEX*16 F1(*)
      COMPLEX*16 TMP4
      COMPLEX*16 VERTEX
      COMPLEX*16 COUP
      P3(0) = DBLE(S3(1))
      P3(1) = DBLE(S3(2))
      P3(2) = DIMAG(S3(2))
      P3(3) = DIMAG(S3(1))
      TMP4 = (F1(5)*-1D0*(P3(1)*R2(9)+P3(2)*R2(13)+P3(3)*R2(17)
     $ -P3(0)*R2(5))-F1(6)*(P3(1)*R2(10)+P3(2)*R2(14)+P3(3)*R2(18)
     $ -P3(0)*R2(6)))
      VERTEX = COUP*-CI * TMP4*S3(3)
      END


C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     P(2,3)*ProjP(2,1)
C     
      SUBROUTINE FRS6_8_0(F1, R2, S3, COUP1, COUP2,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 S3(*)
      COMPLEX*16 R2(*)
      REAL*8 P3(0:3)
      COMPLEX*16 F1(*)
      COMPLEX*16 COUP1
      COMPLEX*16 COUP2
      COMPLEX*16 VERTEX
      COMPLEX*16 TMP
      CALL FRS6_0(F1,R2,S3,COUP1,VERTEX)
      CALL FRS8_0(F1,R2,S3,COUP2,TMP)
      VERTEX = VERTEX + TMP
      END


