C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Gamma(2,2,-1)*ProjP(-1,1)
C     
      SUBROUTINE FRS7_0(F1, R2, S3, COUP,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 S3(*)
      COMPLEX*16 R2(*)
      COMPLEX*16 F1(*)
      COMPLEX*16 VERTEX
      COMPLEX*16 COUP
      COMPLEX*16 TMP9
      TMP9 = (F1(5)*-1D0*(R2(8)+R2(15)+CI*(R2(12))-R2(3))+F1(6)*(R2(4)
     $ +R2(16)+CI*(R2(11))-R2(7)))
      VERTEX = COUP*-CI * TMP9*S3(3)
      END


