C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     (-(Epsilon(2,3,-1,-2)*P(-1,3)*Gamma(-2,2,-3)*ProjM(-3,1)) -
C      complex(0,1)*P(-1,3)*Gamma(-1,2,-2)*Metric(2,3)*ProjM(-2,1) +
C      complex(0,1)*P(2,3)*Gamma(3,2,-1)*ProjM(-1,1)) * C(51,2) *
C      C(52,1)
C     
      SUBROUTINE FRV2C1_0(R2, F1, V3, COUP,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 V3(*)
      COMPLEX*16 R2(*)
      REAL*8 P3(0:3)
      COMPLEX*16 TMP20
      COMPLEX*16 F1(*)
      COMPLEX*16 TMP21
      COMPLEX*16 VERTEX
      COMPLEX*16 COUP
      COMPLEX*16 TMP19
      P3(0) = DBLE(V3(1))
      P3(1) = DBLE(V3(2))
      P3(2) = DIMAG(V3(2))
      P3(3) = DIMAG(V3(1))
      TMP19 = (F1(3)*(P3(0)*(R2(18)*(V3(5)+CI*(V3(4)))+(V3(6)*
     $ -1D0*(R2(14)+CI*(R2(10)))+(R2(13)*V3(4)-R2(9)*V3(5))))
     $ +(P3(1)*(R2(13)*(V3(6)-V3(3))+(V3(5)*(R2(5)-R2(17))+(-CI
     $ *(R2(18)*V3(3))+CI*(R2(6)*V3(6)))))+(P3(2)*(R2(9)*(V3(3)-V3(6))
     $ +(V3(4)*(R2(17)-R2(5))+(R2(6)*V3(6)-R2(18)*V3(3))))+P3(3)
     $ *(R2(6)*-1D0*(V3(5)+CI*(V3(4)))+(V3(3)*(R2(14)+CI*(R2(10)))
     $ +(R2(9)*V3(5)-R2(13)*V3(4)))))))+F1(4)*(P3(0)*(R2(17)*(V3(5)
     $ -CI*(V3(4)))+(V3(6)*(+CI*(R2(9))-R2(13))+(R2(10)*V3(5)
     $ -R2(14)*V3(4))))+(P3(1)*(R2(14)*(V3(6)+V3(3))+(V3(5)*-1D0
     $ *(R2(18)+R2(6))+(-CI*(R2(5)*V3(6))+CI*(R2(17)*V3(3)))))
     $ +(P3(2)*(R2(10)*-1D0*(V3(6)+V3(3))+(V3(4)*(R2(18)+R2(6))
     $ +(R2(5)*V3(6)-R2(17)*V3(3))))+P3(3)*(R2(5)*(+CI*(V3(4))-V3(5))
     $ +(V3(3)*(R2(13)-CI*(R2(9)))+(R2(10)*V3(5)-R2(14)*V3(4))))))))
      TMP20 = -1D0*(F1(3)*(V3(3)*(R2(5)*(P3(0)-P3(3))+R2(6)*(
     $ +CI*(P3(2))-P3(1)))+(V3(4)*(R2(9)*(P3(3)-P3(0))+R2(10)*(P3(1)
     $ -CI*(P3(2))))+(V3(5)*(R2(13)*(P3(3)-P3(0))+R2(14)*(P3(1)
     $ -CI*(P3(2))))+V3(6)*(R2(17)*(P3(3)-P3(0))+R2(18)*(P3(1)
     $ -CI*(P3(2)))))))+F1(4)*(V3(3)*(R2(5)*-1D0*(P3(1)+CI*(P3(2)))
     $ +R2(6)*(P3(0)+P3(3)))+(V3(4)*(R2(9)*(P3(1)+CI*(P3(2)))
     $ -R2(10)*(P3(0)+P3(3)))+(V3(5)*(R2(13)*(P3(1)+CI*(P3(2)))
     $ -R2(14)*(P3(0)+P3(3)))+V3(6)*(R2(17)*(P3(1)+CI*(P3(2)))
     $ -R2(18)*(P3(0)+P3(3)))))))
      TMP21 = -1D0*(F1(3)*(P3(0)*(R2(5)*(V3(3)-V3(6))+R2(6)*(
     $ +CI*(V3(5))-V3(4)))+(P3(1)*(R2(9)*(V3(6)-V3(3))+R2(10)*(V3(4)
     $ -CI*(V3(5))))+(P3(2)*(R2(13)*(V3(6)-V3(3))+R2(14)*(V3(4)
     $ -CI*(V3(5))))+P3(3)*(R2(17)*(V3(6)-V3(3))+R2(18)*(V3(4)
     $ -CI*(V3(5)))))))+F1(4)*(P3(0)*(R2(5)*-1D0*(V3(4)+CI*(V3(5)))
     $ +R2(6)*(V3(3)+V3(6)))+(P3(1)*(R2(9)*(V3(4)+CI*(V3(5)))
     $ -R2(10)*(V3(3)+V3(6)))+(P3(2)*(R2(13)*(V3(4)+CI*(V3(5)))
     $ -R2(14)*(V3(3)+V3(6)))+P3(3)*(R2(17)*(V3(4)+CI*(V3(5)))
     $ -R2(18)*(V3(3)+V3(6)))))))
      VERTEX = COUP*(TMP21+CI*(TMP19)-TMP20)
      END


C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     (-(Epsilon(2,3,-1,-2)*P(-1,3)*Gamma(-2,2,-3)*ProjM(-3,1)) -
C      complex(0,1)*P(-1,3)*Gamma(-1,2,-2)*Metric(2,3)*ProjM(-2,1) +
C      complex(0,1)*P(2,3)*Gamma(3,2,-1)*ProjM(-1,1)) * C(51,2) *
C      C(52,1)
C     
      SUBROUTINE FRV2_4C1_0(R2, F1, V3, COUP1, COUP2,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 V3(*)
      COMPLEX*16 R2(*)
      REAL*8 P3(0:3)
      COMPLEX*16 F1(*)
      COMPLEX*16 COUP2
      COMPLEX*16 COUP1
      COMPLEX*16 VERTEX
      COMPLEX*16 TMP
      CALL FRV2C1_0(R2,F1,V3,COUP1,VERTEX)
      CALL FRV4C1_0(R2,F1,V3,COUP2,TMP)
      VERTEX = VERTEX + TMP
      END


