C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Gamma(1,2,-1)*ProjM(-1,1)
C     
      SUBROUTINE RFS1_0(R1, F2, S3, COUP,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 R1(*)
      COMPLEX*16 S3(*)
      COMPLEX*16 F2(*)
      COMPLEX*16 VERTEX
      COMPLEX*16 TMP29
      COMPLEX*16 COUP
      TMP29 = (F2(5)*(R1(3)+R1(8)+R1(15)-CI*(R1(12)))+F2(6)*(R1(4)
     $ +R1(7)+CI*(R1(11))-R1(16)))
      VERTEX = COUP*-CI * TMP29*S3(3)
      END


C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Gamma(1,2,-1)*ProjM(-1,1)
C     
      SUBROUTINE RFS1_2_3_4_0(R1, F2, S3, COUP1, COUP2, COUP3, COUP4
     $ ,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 R1(*)
      COMPLEX*16 S3(*)
      COMPLEX*16 COUP2
      COMPLEX*16 COUP1
      COMPLEX*16 F2(*)
      COMPLEX*16 COUP3
      COMPLEX*16 VERTEX
      COMPLEX*16 TMP
      COMPLEX*16 COUP4
      CALL RFS1_0(R1,F2,S3,COUP1,VERTEX)
      CALL RFS2_0(R1,F2,S3,COUP2,TMP)
      VERTEX = VERTEX + TMP
      CALL RFS3_0(R1,F2,S3,COUP3,TMP)
      VERTEX = VERTEX + TMP
      CALL RFS4_0(R1,F2,S3,COUP4,TMP)
      VERTEX = VERTEX + TMP
      END


