C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Gamma(1,2,-2)*Gamma(3,-2,-1)*ProjP(-1,1)
C     
      SUBROUTINE RFV3_0(R1, F2, V3, COUP,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 R1(*)
      COMPLEX*16 V3(*)
      COMPLEX*16 TMP38
      COMPLEX*16 F2(*)
      COMPLEX*16 VERTEX
      COMPLEX*16 COUP
      TMP38 = (F2(5)*(V3(3)*(R1(5)+R1(10)+R1(17)-CI*(R1(14)))
     $ +(V3(4)*-1D0*(R1(6)+R1(9)+R1(18)-CI*(R1(13)))+(V3(5)*(
     $ -CI*(R1(9))+CI*(R1(6)+R1(18))-R1(13))-V3(6)*(R1(5)+R1(17)
     $ +CI*(R1(14))-R1(10)))))+F2(6)*(V3(3)*(R1(6)+R1(9)+CI*(R1(13))
     $ -R1(18))+(V3(4)*-1D0*(R1(5)+R1(10)+CI*(R1(14))-R1(17))
     $ +(V3(5)*(-CI*(R1(5))+CI*(R1(10)+R1(17))-R1(14))-V3(6)*(R1(9)
     $ +R1(18)+CI*(R1(13))-R1(6))))))
      VERTEX = COUP*-CI * TMP38
      END


