C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     P(-1,3)*Gamma(-1,-3,-2)*Gamma(2,2,-3)*ProjP(-2,1)
C     
      SUBROUTINE FRS8_0(F1, R2, S3, COUP,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 TMP2
      COMPLEX*16 S3(*)
      COMPLEX*16 R2(*)
      REAL*8 P3(0:3)
      COMPLEX*16 F1(*)
      COMPLEX*16 VERTEX
      COMPLEX*16 COUP
      P3(0) = DBLE(S3(1))
      P3(1) = DBLE(S3(2))
      P3(2) = DIMAG(S3(2))
      P3(3) = DIMAG(S3(1))
      TMP2 = (F1(5)*(P3(0)*(R2(5)+R2(10)+R2(17)+CI*(R2(14)))+(P3(1)
     $ *(R2(18)+CI*(R2(13))-R2(6)-R2(9))+(P3(2)*-1D0*(R2(13)-CI
     $ *(R2(18))+CI*(R2(6)+R2(9)))-P3(3)*(R2(5)+R2(10)+R2(17)
     $ +CI*(R2(14))))))+F1(6)*(P3(0)*(R2(6)+R2(9)-CI*(R2(13))-R2(18))
     $ +(P3(1)*-1D0*(R2(5)+R2(10)+R2(17)+CI*(R2(14)))+(P3(2)*(
     $ +CI*(R2(5)+R2(10)+R2(17))-R2(14))+P3(3)*(R2(6)+R2(9)-CI
     $ *(R2(13))-R2(18))))))
      VERTEX = COUP*-CI * TMP2*S3(3)
      END


