ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      SUBROUTINE COUP4()

      IMPLICIT NONE
      INCLUDE 'model_functions.inc'

      DOUBLE PRECISION PI, ZERO
      PARAMETER  (PI=3.141592653589793D0)
      PARAMETER  (ZERO=0D0)
      INCLUDE 'input.inc'
      INCLUDE 'coupl.inc'
      GC_193 = (MDL_COMPLEXI*MDL_RD5X5)/(MDL_MP*MDL_SQRT__2)
      GC_194 = -((MDL_COMPLEXI*MDL_RD5X5*MDL_SQRT__2)/MDL_MP)
      GC_203 = -((MDL_COMPLEXI*MDL_RD6X3)/(MDL_MP*MDL_SQRT__2))
      GC_204 = (MDL_COMPLEXI*MDL_RD6X3*MDL_SQRT__2)/MDL_MP
      GC_213 = (MDL_COMPLEXI*MDL_RD6X6)/(MDL_MP*MDL_SQRT__2)
      GC_214 = -((MDL_COMPLEXI*MDL_RD6X6*MDL_SQRT__2)/MDL_MP)
      GC_222 = -((MDL_COMPLEXI*MDL_RL1X1)/(MDL_MP*MDL_SQRT__2))
      GC_223 = (MDL_COMPLEXI*MDL_RL1X1*MDL_SQRT__2)/MDL_MP
      GC_228 = -((MDL_COMPLEXI*MDL_RL2X2)/(MDL_MP*MDL_SQRT__2))
      GC_229 = (MDL_COMPLEXI*MDL_RL2X2*MDL_SQRT__2)/MDL_MP
      GC_234 = -((MDL_COMPLEXI*MDL_RL3X3)/(MDL_MP*MDL_SQRT__2))
      GC_235 = (MDL_COMPLEXI*MDL_RL3X3*MDL_SQRT__2)/MDL_MP
      GC_240 = (MDL_COMPLEXI*MDL_RL3X6)/(MDL_MP*MDL_SQRT__2)
      GC_241 = -((MDL_COMPLEXI*MDL_RL3X6*MDL_SQRT__2)/MDL_MP)
      GC_246 = (MDL_COMPLEXI*MDL_RL4X4)/(MDL_MP*MDL_SQRT__2)
      GC_247 = -((MDL_COMPLEXI*MDL_RL4X4*MDL_SQRT__2)/MDL_MP)
      GC_252 = (MDL_COMPLEXI*MDL_RL5X5)/(MDL_MP*MDL_SQRT__2)
      GC_253 = -((MDL_COMPLEXI*MDL_RL5X5*MDL_SQRT__2)/MDL_MP)
      GC_258 = -((MDL_COMPLEXI*MDL_RL6X3)/(MDL_MP*MDL_SQRT__2))
      GC_259 = (MDL_COMPLEXI*MDL_RL6X3*MDL_SQRT__2)/MDL_MP
      GC_264 = (MDL_COMPLEXI*MDL_RL6X6)/(MDL_MP*MDL_SQRT__2)
      GC_265 = -((MDL_COMPLEXI*MDL_RL6X6*MDL_SQRT__2)/MDL_MP)
      GC_270 = -((MDL_COMPLEXI*MDL_RN1X1)/(MDL_MP*MDL_SQRT__2))
      GC_271 = (MDL_COMPLEXI*MDL_RN1X1*MDL_SQRT__2)/MDL_MP
      GC_273 = -((MDL_COMPLEXI*MDL_RN2X2)/(MDL_MP*MDL_SQRT__2))
      END
