C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     P(-1,3)*Gamma(-1,-2,-3)*Gamma(2,2,-2)*ProjM(-3,1)
C     
      SUBROUTINE FRS5_0(F1, R2, S3, COUP,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 S3(*)
      COMPLEX*16 R2(*)
      COMPLEX*16 TMP10
      REAL*8 P3(0:3)
      COMPLEX*16 F1(*)
      COMPLEX*16 VERTEX
      COMPLEX*16 COUP
      P3(0) = DBLE(S3(1))
      P3(1) = DBLE(S3(2))
      P3(2) = DIMAG(S3(2))
      P3(3) = DIMAG(S3(1))
      TMP10 = (F1(3)*(P3(0)*-1D0*(R2(8)+R2(15)+CI*(R2(12))-R2(3))
     $ +(P3(1)*(R2(4)+R2(16)+CI*(R2(11))-R2(7))+(P3(2)*(-CI*(R2(7))
     $ +CI*(R2(4)+R2(16))-R2(11))-P3(3)*(R2(8)+R2(15)+CI*(R2(12))
     $ -R2(3)))))+F1(4)*(P3(0)*(R2(4)+R2(16)+CI*(R2(11))-R2(7))
     $ +(P3(1)*-1D0*(R2(8)+R2(15)+CI*(R2(12))-R2(3))+(P3(2)*(
     $ -CI*(R2(3))+CI*(R2(8)+R2(15))-R2(12))-P3(3)*(R2(4)+R2(16)
     $ +CI*(R2(11))-R2(7))))))
      VERTEX = COUP*-CI * TMP10*S3(3)
      END


