C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     (-(P(-1,3)*Gamma(-1,-3,-2)*Gamma(2,2,-3)*ProjP(-2,1))/2. +
C      P(2,3)*ProjP(2,1)) * C(51,2) * C(52,1)
C     
      SUBROUTINE FRS9C1_0(R2, F1, S3, COUP,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 S3(*)
      COMPLEX*16 R2(*)
      REAL*8 P3(0:3)
      COMPLEX*16 F1(*)
      COMPLEX*16 TMP4
      COMPLEX*16 VERTEX
      COMPLEX*16 COUP
      COMPLEX*16 TMP3
      P3(0) = DBLE(S3(1))
      P3(1) = DBLE(S3(2))
      P3(2) = DIMAG(S3(2))
      P3(3) = DIMAG(S3(1))
      TMP4 = (F1(5)*-1D0*(P3(1)*R2(9)+P3(2)*R2(13)+P3(3)*R2(17)
     $ -P3(0)*R2(5))-F1(6)*(P3(1)*R2(10)+P3(2)*R2(14)+P3(3)*R2(18)
     $ -P3(0)*R2(6)))
      TMP3 = -1D0*(F1(5)*(P3(0)*(R2(10)+R2(17)-CI*(R2(14))-R2(5))
     $ +(P3(1)*(R2(9)+CI*(R2(13))-R2(6)-R2(18))+(P3(2)*(R2(13)
     $ -CI*(R2(9))+CI*(R2(6)+R2(18)))+P3(3)*(R2(10)+R2(17)-CI*(R2(14))
     $ -R2(5)))))+F1(6)*(P3(0)*(R2(9)+CI*(R2(13))-R2(6)-R2(18))
     $ +(P3(1)*(R2(10)+R2(17)-CI*(R2(14))-R2(5))+(P3(2)*(R2(14)
     $ -CI*(R2(5))+CI*(R2(10)+R2(17)))+P3(3)*(R2(6)+R2(18)-CI*(R2(13))
     $ -R2(9))))))
      VERTEX = COUP*1D0/2D0 * S3(3)*(-2D0 * CI*(TMP4)+CI*(TMP3))
      END


