C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     P(-1,3)*Gamma(-1,-3,-2)*Gamma(1,2,-3)*ProjM(-2,1)
C     
      SUBROUTINE RFS2_0(R1, F2, S3, COUP,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 R1(*)
      COMPLEX*16 S3(*)
      REAL*8 P3(0:3)
      COMPLEX*16 F2(*)
      COMPLEX*16 VERTEX
      COMPLEX*16 COUP
      COMPLEX*16 TMP35
      P3(0) = DBLE(S3(1))
      P3(1) = DBLE(S3(2))
      P3(2) = DIMAG(S3(2))
      P3(3) = DIMAG(S3(1))
      TMP35 = (F2(3)*(P3(0)*(R1(3)+CI*(R1(12))-R1(8)-R1(15))+(P3(1)
     $ *(R1(4)+CI*(R1(11))-R1(7)-R1(16))+(P3(2)*-1D0*(R1(11)-CI
     $ *(R1(16))+CI*(R1(4)+R1(7)))+P3(3)*(R1(3)+R1(8)-CI*(R1(12))
     $ -R1(15)))))+F2(4)*(P3(0)*(R1(4)+R1(16)-CI*(R1(11))-R1(7))
     $ +(P3(1)*(R1(3)+R1(15)-CI*(R1(12))-R1(8))+(P3(2)*(+CI*(R1(3)
     $ +R1(8)+R1(15))-R1(12))-P3(3)*(R1(4)+R1(7)+R1(16)+CI*(R1(11)))))
     $ ))
      VERTEX = COUP*-CI * TMP35*S3(3)
      END


