C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Gamma(1,2,-1)*ProjP(-1,1)
C     
      SUBROUTINE RFS3_0(R1, F2, S3, COUP,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 R1(*)
      COMPLEX*16 S3(*)
      COMPLEX*16 TMP34
      COMPLEX*16 F2(*)
      COMPLEX*16 VERTEX
      COMPLEX*16 COUP
      TMP34 = (F2(3)*(R1(5)+CI*(R1(14))-R1(10)-R1(17))+F2(4)*(R1(6)
     $ +R1(18)-CI*(R1(13))-R1(9)))
      VERTEX = COUP*-CI * TMP34*S3(3)
      END


