C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Gamma(1,2,-2)*Gamma(3,-2,-1)*ProjM(-1,1)
C     
      SUBROUTINE RFV1_0(R1, F2, V3, COUP,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 R1(*)
      COMPLEX*16 V3(*)
      COMPLEX*16 F2(*)
      COMPLEX*16 VERTEX
      COMPLEX*16 COUP
      COMPLEX*16 TMP43
      TMP43 = (F2(3)*(V3(3)*(R1(3)+CI*(R1(12))-R1(8)-R1(15))+(V3(4)
     $ *(R1(4)+CI*(R1(11))-R1(7)-R1(16))+(V3(5)*-1D0*(R1(11)-CI
     $ *(R1(16))+CI*(R1(4)+R1(7)))+V3(6)*(R1(3)+R1(8)-CI*(R1(12))
     $ -R1(15)))))+F2(4)*(V3(3)*(R1(4)+R1(16)-CI*(R1(11))-R1(7))
     $ +(V3(4)*(R1(3)+R1(15)-CI*(R1(12))-R1(8))+(V3(5)*(+CI*(R1(3)
     $ +R1(8)+R1(15))-R1(12))-V3(6)*(R1(4)+R1(7)+R1(16)+CI*(R1(11)))))
     $ ))
      VERTEX = COUP*-CI * TMP43
      END


C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Gamma(1,2,-2)*Gamma(3,-2,-1)*ProjM(-1,1)
C     
      SUBROUTINE RFV1_2_3_5_0(R1, F2, V3, COUP1, COUP2, COUP3, COUP4
     $ ,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 R1(*)
      COMPLEX*16 V3(*)
      COMPLEX*16 COUP2
      COMPLEX*16 COUP1
      COMPLEX*16 F2(*)
      COMPLEX*16 TMP
      COMPLEX*16 COUP3
      COMPLEX*16 VERTEX
      COMPLEX*16 COUP4
      CALL RFV1_0(R1,F2,V3,COUP1,VERTEX)
      CALL RFV2_0(R1,F2,V3,COUP2,TMP)
      VERTEX = VERTEX + TMP
      CALL RFV3_0(R1,F2,V3,COUP3,TMP)
      VERTEX = VERTEX + TMP
      CALL RFV5_0(R1,F2,V3,COUP4,TMP)
      VERTEX = VERTEX + TMP
      END


